version: '3'

services:
  db:
    image: mongo:4.2
    volumes:
      - ./data/mongodb:/data/db
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - PORT=8000
      - MONGO_HOST=db
      - MONGO_NAME=robostatus
      - REQ_INTERVAL=20
      - ROBOTOFF_BASE_URL=https://robotoff.wild31.com
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend:/app-data
  frontend:
    build: ./frontend
    # GOD DAMMIT, FUCK!
    # https://stackoverflow.com/questions/60895246/react-app-exiting-in-docker-container-with-exit-code-0
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"

volumes:
  db_data:
  backend_data:
