version: '3'

services:
  db:
    image: mongo:4.2
    volumes:
      - ./data/mongodb:/data/db
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - PORT=8000
      - MONGO_HOST=db
      - MONGO_NAME=robostatus
      - REQ_INTERVAL=60
      # - ROBOTOFF_BASE_URL=https://robotoff.wild31.com
      - ROBOTOFF_BASE_URL=https://robotoff.openfoodfacts.org
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend:/app-data
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL
    ports:
      - "5000:5000"

volumes:
  db_data:
  backend_data:
